export {default as Home} from './Home/Home'
export {default as Favorite} from './Favorite/Favorite'
export {default as Cart} from './Cart/Cart'
export {default as Order} from './OrderHistory/OrderHistory'
export {default as Detail} from './Details/Details'
export {default as Payment} from './Payment/Payment'